Vagrant.configure("2") do |config|
    # Verwende die Windows-Box
    config.vm.box = "gusztavvargadr/windows-10-22h2-enterprise"
  
    # Konfiguriere den Provider, zum Beispiel VirtualBox oder VMware
    config.vm.provider "hyperv" do |vb|
      vb.memory = "4096" # Setze den Arbeitsspeicher auf 4 GB
      vb.cpus = 4 # Verwende 4 CPUs
    end
  
    # Führe das PowerShell-Skript aus
    config.vm.provision "shell", inline: <<-SHELL
      # Installiere XML Notepad über winget
      winget install -e --id Microsoft.XMLNotepad
    SHELL
  end
  