Vagrant.configure("2") do |config|
    # Verwende die Windows-Box
    config.vm.box = "gusztavvargadr/windows-10-22h2-enterprise"
    config.vm.boot_timeout = 360      
  
    # Konfiguriere den Provider, zum Beispiel VirtualBox oder VMware
    config.vm.provider "hyperv" do |vb|
      vb.memory = "4096" # Setze den Arbeitsspeicher auf 4 GB
      vb.cpus = 4 # Verwende 4 CPUs
    end
    
    # Keine SMB Verbindung aufbauen
    config.vm.synced_folder ".", "/vagrant", disabled: true    
  
  end
  